# Generated by Django 4.2.5 on 2024-10-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_task_doer_alter_task_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="year_in_school",
            field=models.CharField(
                choices=[
                    ("FR", "Freshman"),
                    ("SO", "Sophomore"),
                    ("JR", "Junior"),
                    ("SR", "Senior"),
                    ("GR", "Graduate"),
                ],
                default="FR",
                max_length=2,
            ),
        ),
    ]
