# Generated by Django 5.0 on 2023-12-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_shoppingcart_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.CharField(max_length=256, verbose_name="сроки выполнения"),
        ),
    ]
