# Generated by Django 4.2.5 on 2024-10-26 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_remove_task_year_in_school_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="recipes.tag",
                verbose_name="тэги",
            ),
            preserve_default=False,
        ),
    ]
